//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiYouLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultation()
        {
            this.Resultat = new HashSet<Resultat>();
        }
    
        public int ID_Consult { get; set; }
        public int PatientID_P { get; set; }
        public int MedecinID_Med { get; set; }
        public Nullable<System.DateTime> Date_consult { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultat> Resultat { get; set; }
    }
}
