//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiYouLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultat
    {
        public int ID_Res { get; set; }
        public Nullable<float> Float_Valeur { get; set; }
        public int ExamenID_Exam { get; set; }
        public int ConsultationID_Consult { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Examen Examen { get; set; }
    }
}
