//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiYouLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaire
    {
        public int ID_sec { get; set; }
        public string Nom_sec { get; set; }
        public string Prenom_sec { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
    }
}
